/**
 * Verify app against the authentication design system (docs/BRAND-DESIGN-SYSTEM.md
 * §3 and §8): ink token for the scanner ground, a legible customer reference,
 * the monogram where the brand put it (tab icon, landing) beside a word ORBES
 * that stays typed, type set from brand.css tokens, the
 * floors of what is acted on (10 px type, 44 px tap zones; measured in a real
 * page by the E2E suites, test/support/tap-zones.ts), and the shipped display
 * face (Gravesend Sans) on titles and labels of both apps, never on what is
 * read.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { CODE01 } from '../../src/core/code/profile.js';
import { ORBES_CODE_STYLES } from '../../src/core/code/styles.js';
import { computeGenome, genomeLayout } from '../../src/core/genome/index.js';
import { packIdentity } from '../../src/core/identity.js';
import { MONOGRAM_BOUNDS, MONOGRAM_PATHS } from '../../src/core/render/monogram.js';
import { genomeFigureMarkup } from '../../src/web/admin/ui/figures.js';
import { genomeRowMarkup } from '../../src/web/verify/genome-view.js';
import { registrationStatus } from '../../src/web/verify/view-model.js';
import { parseUnicodeRange, readWoff2, woff2CodePoints, woff2Names, woff2WeightClass } from '../support/woff2.js';

const WEB = join(dirname(fileURLToPath(import.meta.url)), '../../src/web');
const styles = readFileSync(join(WEB, 'verify/styles.css'), 'utf8');
const brand = readFileSync(join(WEB, 'shared/brand.css'), 'utf8');
const adminStyles = readFileSync(join(WEB, 'admin/styles.css'), 'utf8');
const resultView = readFileSync(join(WEB, 'verify/views/result.ts'), 'utf8');
const favicon = readFileSync(join(WEB, 'verify/favicon.svg'), 'utf8');

/** Declarations of the first rule whose selector list is exactly `selector`. */
function rule(css: string, selector: string): Record<string, string> {
  const esc = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const m = new RegExp(`(?:^|\\})\\s*${esc}\\s*\\{([^}]*)\\}`, 'm').exec(css);
  if (!m) throw new Error(`no rule ${selector}`);
  const out: Record<string, string> = {};
  for (const decl of m[1].split(';')) {
    const i = decl.indexOf(':');
    if (i > 0) out[decl.slice(0, i).trim()] = decl.slice(i + 1).trim();
  }
  return out;
}

const G184 = computeGenome(packIdentity({ year: 2026, categoryIndex: 1, serial: 184 }), 1);
const GENOME_184 = { id: 'O26-J-00184', version: 'GENOME-01', versionNumber: 1, fingerprint: G184.fingerprint, glyphs: [...G184.glyphs], ids: [...G184.ids] };

const tokens: Record<string, string> = {};
for (const m of brand.matchAll(/^\s*(--[\w-]+):\s*([^;]+);/gm)) tokens[m[1]] = m[2].trim();
const resolve = (v: string): string => v.replace(/var\((--[\w-]+)\)/g, (_, t: string) => tokens[t] ?? t);

describe('verify app: brand deviations (BRAND-DESIGN-SYSTEM §8)', () => {
  it('grounds the scanner in the ink token #0A0A0A, never pure black', () => {
    expect(tokens['--ink']).toBe('#0a0a0a');
    expect(rule(styles, 'body[data-screen="scan"]').background).toBe('var(--ink)');
    expect(rule(styles, '.view--scan').background).toBe('var(--ink)');
    expect(styles).not.toMatch(/#000(000)?\b|\bblack\b|rgba?\(\s*0\s*,\s*0\s*,\s*0\b/i);
  });

  it('draws the GENOME on its ivory plate in the ivory colourway ink (#111111), as it is printed', () => {
    for (const layout of ['orbit', 'row'] as const) {
      const markup = genomeRowMarkup(GENOME_184, { layout });
      expect(markup, layout).not.toBeNull();
      const inks = new Set([...markup!.matchAll(/(?:fill|stroke)="([^"]+)"/g)].map((m) => m[1]).filter((v) => v !== 'none'));
      expect([...inks], layout).toEqual([ORBES_CODE_STYLES.ivory.ink]);
    }
    expect(rule(styles, '.result__genome').background).toBe('var(--ivory)');
    expect(tokens['--ivory']?.toLowerCase()).toBe(ORBES_CODE_STYLES.ivory.paper.toLowerCase());
  });

  it('sets the customer-quotable reference (VERIFIED · REF) at ≥ 10 px in a readable tone', () => {
    const meta = rule(styles, '.result__meta');
    const px = Number.parseFloat(resolve(meta['font-size']));
    expect(px).toBeGreaterThanOrEqual(10);
    // Not the 8 px .nano utility class, and in --ink-soft (6.7 : 1), not --metal.
    const cls = /class: 'result__meta([^']*)'/.exec(resultView)?.[1] ?? '';
    expect(cls).not.toMatch(/\bnano\b/);
    expect(meta.color ?? 'var(--ink-soft)').toMatch(/--ink-soft|--ink\b/);
  });

  it('draws the tab icon from the monogram, in ink on a white disc (BRAND §3.5, §3.9)', () => {
    // Generated by scripts/favicons.ts; test/web/monogram.test.ts checks it byte for byte.
    expect([...favicon.matchAll(/<path d="([^"]+)"\/>/g)].map((m) => m[1])).toEqual(MONOGRAM_PATHS);
    expect(favicon).toContain('<g fill="#0a0a0a" transform="matrix(');
    expect(favicon).toContain('<circle cx="16" cy="16" r="15" fill="#ffffff"/>');
  });

  it('sets type from brand.css tokens wherever a token has the same value', () => {
    const bySize: Record<string, string> = {};
    const byTrack: Record<string, string> = {};
    for (const [t, v] of Object.entries(tokens)) {
      if (t.startsWith('--fs-')) bySize[v] = t;
      if (t.startsWith('--track-')) byTrack[v] = t;
    }
    const literal: string[] = [];
    for (const m of styles.matchAll(/^\s*(font-size|letter-spacing|text-indent):\s*([^;]+);/gm)) {
      const [, prop, value] = m;
      if (prop === 'font-size' && bySize[value]) literal.push(`${prop}: ${value} → var(${bySize[value]})`);
      if (prop !== 'font-size' && byTrack[value]) literal.push(`${prop}: ${value} → var(${byTrack[value]})`);
    }
    expect(literal).toEqual([]);
  });

  it('sets every fixed font size of both apps from a brand.css token (no off-scale literal sizes)', () => {
    const admin = readFileSync(join(WEB, 'admin/styles.css'), 'utf8');
    const literal = [styles, admin].flatMap((css) => [...css.matchAll(/^\s*font-size:\s*([0-9.]+px)\s*;/gm)].map((m) => m[1]));
    expect(literal).toEqual([]);
  });

  it('uses every type token it defines (no dead tokens)', () => {
    const admin = readFileSync(join(WEB, 'admin/styles.css'), 'utf8');
    for (const t of Object.keys(tokens).filter((k) => k.startsWith('--fs-') || k.startsWith('--track-'))) {
      const used = [brand, styles, admin].some((css) => css.includes(`var(${t})`));
      expect(used, t).toBe(true);
    }
  });
});

describe('verify app: floors of 10 px for what is acted on and 44 px for what is tapped (BRAND-DESIGN-SYSTEM §3.8)', () => {
  const all = [...rules(brand), ...rules(styles)];
  const px = (v: string) => Number.parseFloat(resolve(v));
  /** Every rule that styles `cls` itself, alone or compound, in a descendant selector or a media query (not its ::after rule). */
  const about = (cls: string) => {
    const re = new RegExp(`${cls.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![\\w-])`);
    return all.filter((r) => r.selectors.some((s) => re.test(s) && !s.includes('::')));
  };
  // Whatever the app offers to tap shows a pointer: that is how a control is found.
  const interactive = [...new Set(all.filter((r) => r.decls.cursor === 'pointer').flatMap((r) => r.selectors))].sort();

  it('finds every control of the app by its pointer', () => {
    expect(interactive).toEqual(['.auth__option', '.btn', '.scan__control', '.tabs__tab', '.textlink']);
  });

  it('sets no interactive selector under 10 px of type nor under a 44 px minimum height', () => {
    for (const sel of [...interactive, '.field__input']) {
      const base = all.find((r) => r.selectors.includes(sel));
      expect(base?.decls['font-size'], sel).toBeDefined();
      expect(base?.decls['min-height'], sel).toBeDefined();
      // No variant, state, descendant or media rule takes either below its floor.
      for (const r of about(sel)) {
        const where = `${sel} (${r.selectors.join(', ')})`;
        if (r.decls['font-size']) expect(px(r.decls['font-size']), where).toBeGreaterThanOrEqual(10);
        for (const p of ['min-height', 'height', 'max-height']) if (r.decls[p]) expect(px(r.decls[p]), where).toBeGreaterThanOrEqual(44);
      }
    }
    // The zoom shows two characters: its zone is at least as wide as it is high.
    expect(px(rule(styles, '.scan__control')['min-width'])).toBeGreaterThanOrEqual(44);
  });

  it('lets no class the views put on a button or a link take it under either floor', () => {
    // Every class written on an h('button') or h('a') of the verify views (the control classes and those beside
    // them: .scan__zoom, .scan__close, .landing__upload, .contact__phone…), so a rule that names the element by
    // its modifier alone is held to the same floors.
    const sources = readdirSync(join(WEB, 'verify/views')).map((f) => readFileSync(join(WEB, 'verify/views', f), 'utf8'));
    const classes = [
      ...new Set(sources.flatMap((src) => [...src.matchAll(/h\(\s*'(?:button|a)',\s*\{\s*class:\s*'([^']+)'/g)].flatMap((m) => m[1].split(/\s+/)))),
    ].sort();
    expect(classes).toEqual(
      expect.arrayContaining(['auth__option', 'btn', 'btn--block', 'contact__email', 'contact__phone', 'landing__scan', 'landing__upload', 'scan__close', 'scan__control', 'scan__zoom', 'tabs__tab', 'textlink']),
    );
    for (const cls of classes) {
      for (const r of about(`.${cls}`)) {
        const where = `.${cls} (${r.selectors.join(', ')})`;
        if (r.decls['font-size']) expect(px(r.decls['font-size']), where).toBeGreaterThanOrEqual(10);
        for (const p of ['min-height', 'height', 'max-height']) if (r.decls[p]) expect(px(r.decls[p]), where).toBeGreaterThanOrEqual(44);
      }
    }
  });

  it('draws the keyboard focus ring where it was before the tap zones grew, never around the transparent padding', () => {
    // Each control whose zone is transparent padding drops the page's outline and draws its ring with ::before,
    // inset to its former box (plus the outline offset it had), so the ring stays clear of the tab dots and of the
    // switch beside a sign-in option.
    const RINGS: Record<string, string> = {
      '.textlink': '0 -4px',
      '.scan__control': '0 -4px',
      '.scan__control.scan__zoom': '0 7px',
      '.tabs__tab': '1px calc(var(--tab-pad) - 2px) -2px',
      '.auth__option': '4px -4px',
    };
    for (const [sel, inset] of Object.entries(RINGS)) {
      const ring = all.filter((r) => r.selectors.includes(`${sel}:focus-visible::before`));
      expect(ring.at(-1)?.decls.inset, sel).toBe(inset);
    }
    for (const sel of ['.textlink', '.scan__control', '.tabs__tab', '.auth__option']) {
      expect(all.some((r) => r.selectors.includes(`${sel}:focus-visible`) && r.decls.outline === 'none'), sel).toBe(true);
      const ring = all.find((r) => r.selectors.includes(`${sel}:focus-visible::before`))!;
      expect(ring.decls, sel).toMatchObject({ content: '""', position: 'absolute', outline: '1px solid currentColor', 'pointer-events': 'none' });
      // No rule gives the control itself an outline offset any more (it would draw around the zone).
      expect(about(sel).filter((r) => r.selectors.some((s) => s.includes(':focus-visible')) && r.decls['outline-offset'] !== undefined), sel).toEqual([]);
    }
  });

  it('keeps the hairline button for the primary action: the contact of ORBES Client Services is a text link', () => {
    // A result draws one .btn of its own, the foot's SCAN AGAIN or SCAN ANOTHER; the contact, under
    // the help line or in the WARRANTY tab, is a secondary action beside it (§3.8, §4.2).
    const btns = (f: string) => [...readFileSync(join(WEB, 'verify', f), 'utf8').matchAll(/class: '([^']*)'/g)].filter((m) => m[1].split(' ').includes('btn')).length;
    expect(['views/result.ts', 'views/common.ts', 'views/panels.ts', 'views/tabs.ts'].map(btns)).toEqual([1, 0, 0, 0]);
    expect(readFileSync(join(WEB, 'verify/views/common.ts'), 'utf8')).toContain("class: 'textlink contact__email'");
    // No rule restyles it: it takes the text link's 10 px, tracking and 44 px zone as they are.
    expect(about('.contact__email')).toEqual([]);
    // WHERE DID YOU SEE OR BUY THIS PIECE? (under the contact) has no hairline button either: its answers are
    // pressed like the sign-in switch, and SEND is a text link.
    const report = readFileSync(join(WEB, 'verify/views/report.ts'), 'utf8');
    expect(btns('views/report.ts')).toBe(0);
    expect(report).toContain("class: 'auth__option report__channel'");
    expect(report).toContain("class: 'textlink report__send'");
    expect(about('.report__send')).toEqual([]);
  });

  it('draws text links at 80 % ink at rest (11 : 1 on white), no longer 62 %', () => {
    expect(Number(rule(brand, '.textlink').opacity)).toBeGreaterThanOrEqual(0.8);
  });

  it('sets the field labels and the lines that carry a fact at 10 px, leaving 8 px to decoration', () => {
    expect(px(rule(brand, '.field__label')['font-size'])).toBeGreaterThanOrEqual(10);
    expect(px(rule(styles, '.genome__meta')['font-size'])).toBeGreaterThanOrEqual(10);
    // The views set these lines with the 10 px .micro class: the closing time of registration, the
    // transfer code's labels and validity, the signed-in account, the GENOME fingerprint.
    const views = ['views/ownership.ts', 'views/landing.ts', 'views/scanning.ts', 'views/result.ts', 'views/message.ts', 'views/panels.ts', 'views/tabs.ts', 'genome-view.ts', 'main.ts'];
    const classes = views.flatMap((f) => [...readFileSync(join(WEB, 'verify', f), 'utf8').matchAll(/class: '([^']+)'/g)].map((m) => m[1]));
    for (const line of ['ownership__meta', 'transfer-code__label', 'ownership__who', 'genome__meta']) {
      const set = classes.filter((c) => c.split(' ').includes(line) && !c.split(' ').includes('prose'));
      expect(set.length, line).toBeGreaterThan(0);
      for (const c of set) expect(c.split(' '), c).toContain('micro');
    }
    // The 8 px .nano class is left to the landing foot (© ORBES · GENOME CODE · PARIS).
    expect(classes.filter((c) => c.split(' ').includes('nano'))).toEqual(['landing__meta nano']);
  });
});

/** Every innermost rule of a stylesheet (inside @media too): its selectors and declarations. */
function rules(css: string): { selectors: string[]; decls: Record<string, string> }[] {
  const out: { selectors: string[]; decls: Record<string, string> }[] = [];
  for (const m of css.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
    const decls: Record<string, string> = {};
    for (const decl of m[2].split(';')) {
      const i = decl.indexOf(':');
      if (i > 0) decls[decl.slice(0, i).trim()] = decl.slice(i + 1).trim();
    }
    out.push({ selectors: m[1].split(',').map((s) => s.trim().replace(/\s+/g, ' ')), decls });
  }
  return out;
}

/** Selectors set in the display face (font-family: var(--font-display)). */
const displaySelectors = (css: string): string[] => rules(css).filter((r) => r.decls['font-family'] === 'var(--font-display)').flatMap((r) => r.selectors);

const FONT_FILE = join(WEB, 'shared/fonts/gravesend-sans-500.woff2');

describe('display face: Gravesend Sans for the wordmark, titles and labels (BRAND-DESIGN-SYSTEM §3.1, §8 item 18)', () => {
  const face = rules(brand).find((r) => r.selectors[0] === '@font-face')!.decls;
  const font = readWoff2(readFileSync(FONT_FILE));

  it('declares the shipped WOFF2 in @font-face: Gravesend Sans, weight 500, font-display swap', () => {
    expect(face['font-family']).toBe('"Gravesend Sans"');
    expect(face.src).toBe('url("./fonts/gravesend-sans-500.woff2") format("woff2")');
    expect(existsSync(join(WEB, 'shared', 'fonts', 'gravesend-sans-500.woff2'))).toBe(true);
    expect(face['font-display']).toBe('swap');
    expect(face['font-style']).toBe('normal');
    // The one cut supplied: Medium. The declared weight is the file's own.
    expect(face['font-weight']).toBe('500');
    expect(woff2WeightClass(font)).toBe(500);
    expect(rules(brand).filter((r) => r.selectors[0] === '@font-face')).toHaveLength(1);
  });

  it('keeps Helvetica Neue for reading and puts Gravesend first in --font-display, then the same stack', () => {
    const families = (v: string) => resolve(v).split(',').map((f) => f.trim());
    // --font is the stack of theorbes.com (index.html), unchanged: reading text, values and inputs.
    expect(tokens['--font']).toBe('"Helvetica Neue", HelveticaNeue, Helvetica, Arial, sans-serif');
    expect(families(tokens['--font-display'])).toEqual(['"Gravesend Sans"', ...families(tokens['--font'])]);
    expect(families(tokens['--font-display']).at(-1)).toBe('sans-serif');
    // The page default reads; the display face is opted into, role by role.
    expect(rules(brand).find((r) => r.selectors.includes('body'))?.decls['font-family']).toBe('var(--font)');
  });

  it('ships exactly the declared subset (Basic Latin and the brand punctuation), with its licence names', () => {
    expect(font.flavor).toBe('OTTO');
    const declared = parseUnicodeRange(face['unicode-range']);
    expect([...woff2CodePoints(font)].sort((a, b) => a - b)).toEqual([...declared].sort((a, b) => a - b));
    for (let c = 0x20; c <= 0x7e; c++) expect(declared.has(c), `U+${c.toString(16)}`).toBe(true);
    // The punctuation the interfaces set in titles and labels: · — – … × → ’ © (copy.ts, views).
    for (const ch of '·—–…×→’©') expect(declared.has(ch.codePointAt(0)!), ch).toBe(true);
    // The copyright and designer names travel with the file (NOTICE.md).
    const names = woff2Names(font);
    expect(names.get(0)).toMatch(/Rian Hughes \/ Device/);
    expect(names.get(16) ?? names.get(1)).toBe('Gravesend Sans');
    // A preload on the critical path: kept small.
    expect(readFileSync(FONT_FILE).length).toBeLessThan(16 * 1024);
  });

  const BRAND_DISPLAY = ['.wordmark', '.btn', '.textlink', '.field__label'];
  const VERIFY_DISPLAY = ['.landing__sub', '.landing__meta', '.scan__status', '.scan__control', '.verifying__status', '.message__title', '.result__title', '.genome__label', '.tabs__tab', '.rows__label', '.section-label', '.ownership__status', '.result__card-title', '.report__title', '.report__status', '.auth__option'];
  const ADMIN_DISPLAY = ['.side__group-title', '.side__link', '.page-head__eyebrow', '.page-head__title', '.panel__title', '.kpi__label', '.deflist__label', '.table th', '.cbtn', '.cfield__label', '.login__title'];
  // What is read, quoted or compared stays in --font: sentences, values, identifiers, codes, inputs,
  // and the lines that can carry a figure (Gravesend's one is its capital I).
  const VERIFY_READ = ['.prose', '.field__input', '.field__input--code', '.field__hint', '.result__message', '.result__notice', '.result__footnote', '.result__meta', '.genome__id', '.genome__meta', '.lines__line', '.rows__value', '.transfer-code__value', '.transfer-code__label', '.scan__hint', '.scan__zoom', '.form__error', '.ownership__meta', '.ownership__who', '.ownership__email', '.contact__phone', '.contact__hours'];
  const ADMIN_READ = ['.mono', '.status', '.kpi__value', '.kpi__note', '.bar__label', '.deflist__value', '.table', '.cinput', '.sheet__id', '.sheet__plain', '.gen__identity-id', '.claim__code', '.enrol__code', '.enrol__step', '.timeline__move', '.pager__range', '.pager__page', '.topbar__clock', '.topbar__crumb', '.panel__note', '.dialog__eyebrow', '.dialog__title', '.cfield__phrase', '.page-head__title--id', '.side__who', '.side__role'];

  it('sets the wordmark, titles and tracked-capital labels of both apps in the display face', () => {
    expect(displaySelectors(brand)).toEqual(BRAND_DISPLAY);
    expect(displaySelectors(styles)).toEqual(expect.arrayContaining(VERIFY_DISPLAY));
    expect(displaySelectors(adminStyles)).toEqual(expect.arrayContaining(ADMIN_DISPLAY));
  });

  it('never sets what is read in the display face', () => {
    const display = new Set([...displaySelectors(brand), ...displaySelectors(styles), ...displaySelectors(adminStyles)]);
    for (const s of [...VERIFY_READ, ...ADMIN_READ]) expect(display.has(s), s).toBe(false);
    // Gravesend has proportional figures only and one weight: a display role never asks for
    // tabular numerals, nor for a bold the browser would have to fake.
    for (const css of [brand, styles, adminStyles]) {
      for (const r of rules(css)) {
        if (!r.selectors.some((s) => display.has(s))) continue;
        expect(r.decls['font-variant-numeric'] ?? '', r.selectors.join(', ')).not.toMatch(/tabular-nums/);
        expect(Number(r.decls['font-weight'] ?? 400), r.selectors.join(', ')).toBeLessThan(600);
      }
    }
  });

  it('sets a figure in the reading face where a display role may show one (Gravesend\'s one is its capital I)', () => {
    // The overrides come after the display rule of their stylesheet, so they win at equal specificity.
    for (const [css, selector] of [[styles, '.scan__zoom'], [styles, '.contact__phone'], [adminStyles, '.page-head__title--id'], [adminStyles, '.cfield__phrase']] as const) {
      const all = rules(css);
      const at = all.findIndex((r) => r.selectors.includes(selector));
      expect(all[at]?.decls['font-family'], selector).toBe('var(--font)');
      expect(at, selector).toBeGreaterThan(all.findIndex((r) => r.decls['font-family'] === 'var(--font-display)'));
    }
    // The zoom control (1×, 2×), the phone of ORBES Client Services and every console page titled with a product id use them.
    expect(readFileSync(join(WEB, 'verify/views/scanning.ts'), 'utf8')).toContain("class: 'scan__control scan__zoom'");
    expect(readFileSync(join(WEB, 'verify/views/common.ts'), 'utf8')).toContain("class: 'textlink contact__phone'");
    for (const view of ['product', 'generator']) {
      const src = readFileSync(join(WEB, `admin/views/${view}.ts`), 'utf8');
      const titled = (src.match(/title: p\.productId,/g) ?? []).length;
      expect(titled, view).toBeGreaterThan(0);
      expect((src.match(/title: p\.productId,\n\s*identifier: true,/g) ?? []).length, view).toBe(titled);
    }
    // A dialog's eyebrow names the product, key or anomaly it acts on, so it has no display rule at all;
    // the phrase to type in a confirmation (REVOKE O26-J-00184) is a --font span inside its label;
    // and no field label is written with a figure (its range or example goes in the hint, read in --font).
    expect(rules(adminStyles).some((r) => r.selectors.includes('.dialog__eyebrow') && r.decls['font-family'] !== undefined)).toBe(false);
    // (The phrase may depend on the fields, a ticked box that revokes a code: the span is filled as they change.)
    const dialogSrc = readFileSync(join(WEB, 'admin/ui/dialog.ts'), 'utf8');
    expect(dialogSrc).toContain("const phraseText = h('span', { class: 'cfield__phrase' });");
    expect(dialogSrc).toContain("h('span', null, 'Type ', phraseText, ' to confirm')");
    expect(dialogSrc).toContain("phraseText.textContent = p ?? '';");
    for (const view of readdirSync(join(WEB, 'admin/views'))) {
      const src = readFileSync(join(WEB, 'admin/views', view), 'utf8');
      const labels = [...src.matchAll(/\blabel: '([^']*)'/g), ...src.matchAll(/\bfield\('([^']*)'/g)].map((m) => m[1]);
      for (const l of labels) expect(/[0-9]/.test(l) && !/^(Payload SHA-256|Public key \(base64url\))$/.test(l), `${view}: ${l}`).toBe(false);
    }
  });

  it('names fonts only through the tokens (--font, --font-display, the console --mono)', () => {
    for (const [name, css] of [['brand.css', brand], ['verify', styles], ['admin', adminStyles]] as const) {
      const families = rules(css)
        .filter((r) => r.selectors[0] !== '@font-face')
        .map((r) => r.decls['font-family'])
        .filter((v): v is string => v !== undefined);
      for (const v of families) expect(['var(--font)', 'var(--font-display)', 'var(--mono)'], `${name}: ${v}`).toContain(v);
      expect(css, name).not.toMatch(/(?<!-)font:\s*[^;]*(Gravesend|Helvetica)/);
    }
  });
});

describe('verify app: the monogram beside the word ORBES (BRAND-DESIGN-SYSTEM §3.9, §8 item 1)', () => {
  const landing = readFileSync(join(WEB, 'verify/views/landing.ts'), 'utf8');

  it('puts the monogram over the typed wordmark of the landing, inside the heading and decorative there', () => {
    const title = landing.slice(landing.indexOf("{ class: 'landing__title', id: 'landing-title' }"), landing.indexOf("'AUTHENTICATION'"));
    expect(title).toMatch(/monogramSvg\(\{ class: 'landing__monogram', decorative: true \}\),\s*h\('span', \{ class: 'wordmark landing__wordmark', text: 'ORBES' \}\)/);
    expect(landing).toContain("import { monogramSvg } from '../../shared/monogram.js';");
    // brand.css draws it as a block that keeps the ratio of its ink box; the landing sizes it and gives it its clear space.
    expect(rule(brand, '.monogram')).toMatchObject({ display: 'block', height: 'auto', 'aspect-ratio': `${MONOGRAM_BOUNDS.w} / ${MONOGRAM_BOUNDS.h}` });
    expect(rule(styles, '.landing__monogram').width).toBe('min(clamp(64px, 19.5vw, 84px), var(--orbit) * 0.3)');
  });

  it('keeps the word ORBES typed, in the display face, wherever it was: the emblem never replaces it', () => {
    const views = { 'views/landing.ts': 'wordmark landing__wordmark', 'views/result.ts': 'wordmark wordmark--small result__wordmark', 'views/scanning.ts': 'wordmark wordmark--small scan__wordmark' };
    for (const [file, cls] of Object.entries(views)) {
      expect(readFileSync(join(WEB, 'verify', file), 'utf8'), file).toMatch(new RegExp(`class: '${cls}'[^)]*text: 'ORBES'`));
    }
    expect(displaySelectors(brand)).toContain('.wordmark');
    // The result and the scanner keep the word alone (the brand's choice: the emblem marks the landing).
    for (const file of ['views/result.ts', 'views/scanning.ts']) expect(readFileSync(join(WEB, 'verify', file), 'utf8'), file).not.toContain('monogram');
  });
});

describe('verify app: the GENOME in its orbit, as on the piece (BRAND-DESIGN-SYSTEM §2.3, §2.6)', () => {
  it('draws the result GENOME in the orbit layout, the figure of the console and of the code', () => {
    const view = readFileSync(join(WEB, 'verify/genome-view.ts'), 'utf8');
    const block = view.slice(view.indexOf('export function genomeBlock'));
    expect(block).toContain("genomeRow(m, { layout: 'orbit' })");
    // The same core renderer, the same ink and the same geometry as the console's product page.
    const json = { id: 'g', productId: GENOME_184.id, version: 1, versionLabel: 'GENOME-01', value: G184.value, glyphs: [...G184.glyphs], ids: [...G184.ids], pattern: '', fingerprint: G184.fingerprint, createdAt: '2026-01-01T00:00:00.000Z' };
    expect(genomeRowMarkup(GENOME_184, { layout: 'orbit' })).toBe(genomeFigureMarkup(json, 'orbit'));
    // The seal at the centre, then one group per glyph (glyph 0 at north, clockwise: genomeLayout).
    const markup = genomeRowMarkup(GENOME_184, { layout: 'orbit' })!;
    expect(markup.match(/data-layer="seal"/g)).toHaveLength(1);
    expect(markup.match(/data-layer="genome"/g)).toHaveLength(CODE01.genome.count);
  });

  it('sizes the orbit as a centred square of min(64vw, 260px): glyphs of about 43 px, never under the 12 px floor', () => {
    const orbit = rule(styles, '.genome-svg--orbit');
    expect(orbit.width).toBe('min(64vw, 260px)');
    expect(orbit['aspect-ratio']).toBe('1');
    expect(orbit.margin).toBe('0 auto');
    const { viewBox, glyphRadius } = genomeLayout(G184, 'orbit');
    expect(viewBox.w).toBe(viewBox.h);
    const glyphPx = (side: number) => (side * 2 * glyphRadius) / viewBox.w;
    expect(glyphPx(260)).toBeCloseTo(43, 0);
    // 390 px phone: 64vw = 249.6 px; the smallest phone in use (320 px) still draws 34 px glyphs.
    expect(glyphPx(0.64 * 390)).toBeGreaterThan(41);
    expect(glyphPx(0.64 * 320)).toBeGreaterThan(12);
    // The ivory plate keeps its margins (§2.5: 34 / 22 / 28 px).
    expect(rule(styles, '.result__genome').padding).toBe('34px 22px 28px');
    expect(rule(styles, '.result__genome')['margin-top']).toBe('52px');
  });
});

describe('verify app: OWNERSHIP heading follows the registration window', () => {
  const now = Date.parse('2026-10-01T08:30:00.000Z');
  it('says REGISTRATION OPEN only while the scan token is valid', () => {
    expect(registrationStatus('2026-10-01T08:45:00.000Z', now)).toBe('REGISTRATION OPEN');
    expect(registrationStatus('2026-10-01T08:30:00.000Z', now)).toBe('REGISTRATION CLOSED');
    expect(registrationStatus('garbage', now)).toBe('REGISTRATION CLOSED');
  });

  it('builds the heading of the register block from it', () => {
    const src = readFileSync(join(WEB, 'verify/views/ownership.ts'), 'utf8');
    const block = src.slice(src.indexOf('private registerBlock'), src.indexOf('private yoursBlock'));
    expect(block).toContain('registrationStatus(');
    expect(block).not.toMatch(/this\.status\('REGISTRATION OPEN'\)/);
  });
});

describe('GENOME-01 vocabulary specimen (docs/assets/genome-01-vocabulary.svg)', () => {
  const svg = readFileSync(join(WEB, '../../../docs/assets/genome-01-vocabulary.svg'), 'utf8');
  const colours = new Set([...svg.matchAll(/(?:fill|stroke)="(#[0-9a-fA-F]{6})"/g)].map((m) => m[1].toLowerCase()));

  it('is printed on brand ivory with brand greys only (ivory colourway ink #111111, --ink-soft)', () => {
    expect(svg).toContain('fill="#f6f2ea"');
    expect([...colours].sort()).toEqual(['#111111', '#5c5c5c', '#f6f2ea']);
  });
});
