/**
 * The type of the certificate card 79t (plan NEXT LOT §3.2, step 2.1):
 * render/card-type.ts, the glyph outlines scripts/card-type.py generated, and
 * render/card-text.ts, which sets runs with them by their ink edge as 79t's
 * build.py sets its text.
 *
 * The widths build.py printed for 79t (`ORBES w 11.67 ref w 13.86 genome w
 * 15.35 model w 18.98 size w 16.83`, `claim ink w 33.26`, `year w 7.76`) are
 * its metrics: advance widths without kerning, less the side bearings at both
 * ends. card-text reproduces them within 0.05 mm, and kerns what it draws.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { CARD_FACES, capRatio, cardFmt, cardInkWidth, cardMetrics, cardRun, cardText, digitParts, drawable, type CardFaceName } from '../../src/server/render/card-text.js';
import { CARD_TYPE_SOURCES } from '../../src/server/render/card-type.js';

const GENOME = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-·./ ';
const width = (r: { inkLeft: number; inkRight: number }) => r.inkRight - r.inkLeft;

/** Every coordinate pair of absolute path data (M L Q C), as [x, y]. */
function coords(d: string): [number, number][] {
  const n = [...d.matchAll(/-?\d+(?:\.\d+)?/g)].map((m) => Number(m[0]));
  const out: [number, number][] = [];
  for (let i = 0; i + 1 < n.length; i += 2) out.push([n[i], n[i + 1]]);
  return out;
}

describe('card type (render/card-type.ts, generated by scripts/card-type.py)', () => {
  it('names its sources by SHA-256: the Gravesend file is the one the app serves', () => {
    const served = readFileSync(join(GENOME, CARD_TYPE_SOURCES.gravesend.file));
    expect(createHash('sha256').update(served).digest('hex')).toBe(CARD_TYPE_SOURCES.gravesend.sha256);
    expect(CARD_TYPE_SOURCES.helveticaNeue).toMatchObject({ file: '/System/Library/Fonts/HelveticaNeue.ttc', faces: { regular: 0, light: 7 } });
    expect(CARD_TYPE_SOURCES.helveticaNeue.sha256).toMatch(/^[0-9a-f]{64}$/);
  });

  it('holds every character of the card in each face: A–Z, 0–9, the hyphen, the middle dot, the full stop, the slash and the space', () => {
    for (const name of Object.keys(CARD_FACES) as CardFaceName[]) {
      const f = CARD_FACES[name];
      expect(f.unitsPerEm, name).toBe(1000);
      for (const c of CHARSET) expect(f.glyphs[c], `${name} ${JSON.stringify(c)}`).toBeDefined();
      expect(f.glyphs[' '].b, name).toBeNull();
      // Outlines only: absolute moves, lines, quadratic and cubic curves.
      for (const [c, g] of Object.entries(f.glyphs)) expect(g.d, `${name} ${c}`).toMatch(/^(?:[MLQCZ][-\d. ]*)*$/);
    }
    // The cap heights build.py sets its runs with (G_CAP 0.640, H_CAP 0.714).
    expect(capRatio('gravesend')).toBe(0.64);
    expect(capRatio('regular')).toBe(0.714);
    expect(capRatio('light')).toBe(0.714);
  });

  it('kerns as the faces do: Gravesend from its GPOS, Helvetica Neue from its kern table', () => {
    expect(Object.keys(CARD_FACES.gravesend.kern).length).toBeGreaterThan(100);
    expect(CARD_FACES.regular.kern.AV).toBe(-46);
    expect(CARD_FACES.light.kern.AV).toBe(-50);
  });
});

describe('card text (render/card-text.ts)', () => {
  it("reproduces the widths 79t's build.py printed, within 0.05 mm", () => {
    const cases: [string, number, number][] = [
      // ORBES: Gravesend 2.0 mm, tracked 0.62 em.
      ['ORBES', cardMetrics('ORBES', { face: 'gravesend', size: 2, tracking: 0.62 }).ink, 11.67],
      // The serial: Helvetica Neue Light 2.2 mm, tracked 0.05 em.
      ['serial', cardMetrics('O26-J-00184', { face: 'light', size: 2.2, tracking: 0.05 }).ink, 13.86],
      // GENOME G1-E1DC-BE52: Gravesend 1.0 mm, the fingerprint in Helvetica Neue Regular at Gravesend's cap height.
      ['GENOME line', width(cardRun([{ text: 'GENOME ', face: 'gravesend' }, { text: 'G1-E1DC-BE52', face: 'regular' }], { x: 0, baseline: 0, size: 1, tracking: 0.24 })), 15.35],
      // Line 1: Gravesend 1.2 mm, tracked 0.2 em.
      ['line 1', cardMetrics('MONOLITHE · BRACELET', { face: 'gravesend', size: 1.2, tracking: 0.2 }).ink, 18.98],
      // build.py's « size w 16.83 » (the plan's « line 2 ») is the run under the variant line: 925 STERLING SILVER.
      ['925 STERLING SILVER', width(cardRun(digitParts('925 STERLING SILVER'), { x: 0, baseline: 0, size: 1.2, tracking: 0.2 })), 16.83],
      // The claim code: Helvetica Neue Light 3.645 mm (cap 2.60), tracked 0.032 em: the column's measure.
      ['claim code', cardMetrics('7MSE-SK34-PWMC', { face: 'light', size: 3.645, tracking: 0.032 }).ink, 33.26],
      // The year: Gravesend 2.4 mm, tracked 0.40 em.
      ['year', cardMetrics('2026', { face: 'gravesend', size: 2.4, tracking: 0.4 }).ink, 7.76],
    ];
    for (const [name, got, want] of cases) expect(Math.abs(got - want), `${name}: ${got}`).toBeLessThanOrEqual(0.05);
  });

  it('places a run by its ink: the start, the centre or the end at x, whatever the first glyph\'s side bearing', () => {
    const spec = { face: 'light' as const, size: 3.645, tracking: 0.032, baseline: 50.5 };
    const start = cardText('7MSE-SK34-PWMC', { ...spec, x: 48.0052875 });
    const middle = cardText('7MSE-SK34-PWMC', { ...spec, x: 64.6356, align: 'middle' });
    const end = cardText('7MSE-SK34-PWMC', { ...spec, x: 81.2659125, align: 'end' });
    expect(start.inkLeft).toBeCloseTo(48.0052875, 9);
    expect(start.inkRight).toBeCloseTo(81.2659125, 5);
    expect((middle.inkLeft + middle.inkRight) / 2).toBeCloseTo(64.6356, 9);
    expect(end.inkRight).toBeCloseTo(81.2659125, 9);
    // The drawn outlines' extreme points sit on the computed ink (curves' control points may reach a hair beyond).
    const xs = coords(start.d).map(([x]) => x);
    expect(Math.min(...xs)).toBeGreaterThan(48.0052875 - 0.01);
    expect(Math.max(...xs)).toBeLessThan(81.2659125 + 0.01);
  });

  it('draws filled outlines in page millimetres, y down from the baseline: a cap sits between baseline − cap height and the baseline', () => {
    const r = cardText('H', { face: 'gravesend', size: 10, tracking: 0, x: 0, baseline: 20 });
    const ys = coords(r.d).map(([, y]) => y);
    expect(Math.max(...ys)).toBeCloseTo(20, 2);
    expect(Math.min(...ys)).toBeCloseTo(20 - 6.4, 2);
    expect(r.d).not.toMatch(/[^MLQCZ\d. -]/);
  });

  it('kerns what it draws unless told not to, and computes positions without kerning, as build.py', () => {
    const spec = { face: 'gravesend' as const, size: 1.2, tracking: 0.2 };
    const kerned = cardText('MONOLITHE · BRACELET', { ...spec, x: 0, baseline: 0 });
    const flat = cardText('MONOLITHE · BRACELET', { ...spec, x: 0, baseline: 0, kerning: false });
    expect(kerned.inkLeft).toBe(flat.inkLeft);
    expect(kerned.d).not.toBe(flat.d);
    expect(cardInkWidth('MONOLITHE · BRACELET', spec)).toBeLessThan(cardInkWidth('MONOLITHE · BRACELET', { ...spec, kerning: false }));
    expect(cardInkWidth('MONOLITHE · BRACELET', { ...spec, kerning: false })).toBeCloseTo(cardMetrics('MONOLITHE · BRACELET', spec).ink, 9);
  });

  it('sets Helvetica Neue parts at Gravesend\'s cap height with the same tracking in millimetres, each part from the end of the one before', () => {
    const run = cardRun(
      [
        { text: 'SIZE ', face: 'gravesend' },
        { text: '17', face: 'regular' },
      ],
      { x: 10, baseline: 30, size: 1.2, tracking: 0.2 },
    );
    const words = cardText('SIZE ', { face: 'gravesend', size: 1.2, tracking: 0.2, x: 10, baseline: 30 });
    const hfs = (1.2 * 0.64) / 0.714;
    const digitsLsb = cardMetrics('17', { face: 'regular', size: hfs, tracking: (0.2 * 1.2) / hfs }).lsb;
    // The digits start at the words' end (no ink edge in between): their ink at words.end + their own bearing.
    const ys = coords(run.d.slice(words.d.length)).map(([, y]) => y);
    expect(Math.min(...ys)).toBeCloseTo(30 - 1.2 * 0.64, 2);
    expect(run.end).toBeCloseTo(words.end + cardMetrics('17', { face: 'regular', size: hfs, tracking: (0.2 * 1.2) / hfs }).advance, 9);
    expect(digitsLsb).toBeGreaterThan(0);
    expect(digitParts('925 STERLING SILVER')).toEqual([
      { text: '925', face: 'regular' },
      { text: ' STERLING SILVER', face: 'gravesend' },
    ]);
    expect(digitParts('BLUE  ·  SIZE 17.5')).toEqual([
      { text: 'BLUE  ·  SIZE ', face: 'gravesend' },
      { text: '17', face: 'regular' },
      { text: '.', face: 'gravesend' },
      { text: '5', face: 'regular' },
    ]);
  });

  it('drops a character the face has no outline for, and draws nothing for an empty run', () => {
    expect(drawable('MONOLITHE ÉTÉ & CO', 'gravesend')).toBe('MONOLITHE T  CO');
    expect(cardText('', { face: 'gravesend', size: 1, tracking: 0, x: 3, baseline: 4 }).d).toBe('');
    expect(cardRun([], { x: 3, baseline: 4, size: 1, tracking: 0 })).toEqual({ d: '', inkLeft: 3, inkRight: 3, end: 3 });
    expect(cardFmt(-0.0001)).toBe('0');
    expect(cardFmt(1.23456)).toBe('1.235');
  });
});
