/** Server-side artifact rendering: SVG (core renderer), PNG (resvg), PDF (pdfkit, pure vector); certificate cards. */
export {
  ARTIFACT_DEFAULTS,
  ARTIFACT_FORMATS,
  ARTIFACT_LIMITS,
  ArtifactOptionsError,
  CONTENT_TYPES,
  MAX_SHEET_ITEMS,
  artifactFilename,
  isArtifactFormat,
  renderArtifact,
  renderPrintSheet,
  resolveArtifactOptions,
  type ArtifactFormat,
  type ArtifactInput,
  type ArtifactMeta,
  type ArtifactOptions,
  type PrintSheetItem,
  type PrintSheetOptions,
  type RenderedArtifact,
  type ResolvedArtifactOptions,
} from './artifact.js';
export {
  CARD_LAYOUT,
  CERTIFICATE_CARD,
  CERTIFICATE_COPY,
  CERTIFICATE_FORMATS,
  CERTIFICATE_LAYOUT_STATUS,
  CERTIFICATE_LAYOUTS,
  CERTIFICATE_SHEET,
  CertificateInputError,
  MAX_CERTIFICATE_ITEMS,
  SCRATCH_OFF_SPOT,
  certificateCardSvg,
  certificatesCsv,
  csvField,
  layoutCertificateCard,
  layoutCertificateSheet,
  renderCertificateCsv,
  renderCertificatePdf,
  type CertificateCard,
  type CertificateFormat,
  type CertificateItem,
  type CertificateLayout,
  type CertificateLayoutStatus,
  type CertificateOptions,
  type RenderedCertificates,
} from './certificate.js';
export { renderPdf, sceneToPdf, type PdfMeta, type PdfPage, type PdfPlacement, type PdfShape, type PdfSpotColor } from './pdf.js';
export { PNG_SIGNATURE, pixelsFor, readPngDpi, setPngDpi, svgToPng } from './png.js';
export {
  LABEL_LAYOUT,
  SHEET_FOOTER_MM,
  SHEET_PAGES,
  buildArtifactScene,
  cropMarks,
  gridCutMarks,
  labelStrokes,
  layoutSheet,
  sceneToSvg,
  sheetFooter,
  type SheetLayout,
  type SheetPageSize,
} from './print-sheet.js';
export { LABEL_CHARSET, measureText, textRun, toLabelText } from './label-font.js';
export {
  ARTIFACT_THEMES,
  ARTIFACT_THEME_NAMES,
  DEPRECATED_THEME_ALIASES,
  mixTone,
  mmToPt,
  normalizeArtifactTheme,
  type ArtifactScene,
  type ArtifactTheme,
  type ArtifactThemeInput,
  type StrokePath,
  type ViewBox,
} from './scene.js';
