/**
 * Signing keys: rotate (new ACTIVE key, previous one RETIRED and
 * verify-only), retire, revoke (with an optional compromise time that
 * bounds which historical codes stay trusted). Private keys never reach the
 * console: only public keys and registry metadata are listed.
 */
import { h } from '../../shared/dom.js';
import { formatDateTime, humanize, shortHash } from '../format.js';
import { can } from '../model/permissions.js';
import { compromiseTime, confirmationPhrase, keyActions } from '../model/registry.js';
import { toneOf } from '../model/tone.js';
import type { KeyJson } from '../types.js';
import { button, copyButton, mono, pageHeader, statusMark, table } from '../ui/components.js';
import { openDialog } from '../ui/dialog.js';
import { notify } from '../ui/toast.js';
import type { ViewContext } from './context.js';

export async function keysView(ctx: ViewContext): Promise<HTMLElement> {
  const { items } = await ctx.api.keys();
  const keys = [...items].sort((a, b) => b.keyId - a.keyId);
  const manage = can(ctx.session.admin.role, 'manageKeys');
  const active = keys.find((k) => k.status === 'ACTIVE') ?? null;

  const after = (msg: string) => (r: unknown) => {
    if (!r) return;
    notify(msg);
    ctx.reload();
  };

  const rotate = () =>
    void openDialog({
      title: 'Rotate the signing key',
      eyebrow: 'Keys',
      danger: true,
      body: [
        h('p', { class: 'dialog__text' }, `A new Ed25519 key is generated by the key provider and becomes ACTIVE.${active ? ` Key #${active.keyId} becomes RETIRED: it no longer signs but its codes keep verifying.` : ''}`),
      ],
      fields: [{ name: 'kid', label: 'Key label (optional)', maxlength: 64, hint: 'Defaults to a generated kid.' }],
      phrase: confirmationPhrase('rotate-key', ''),
      confirmLabel: 'Rotate key',
      submit: async (v) => {
        await ctx.api.rotateKey(v.kid?.trim() || undefined);
      },
    }).then(after('New signing key active.'));

  const retire = (k: KeyJson) =>
    void openDialog({
      title: `Retire key #${k.keyId}`,
      eyebrow: k.kid,
      danger: true,
      body: h('p', { class: 'dialog__text' }, 'The key stops signing; codes it signed keep verifying. Issuance halts until a new key is rotated in.'),
      phrase: confirmationPhrase('retire-key', k.keyId),
      confirmLabel: 'Retire key',
      submit: async () => {
        await ctx.api.retireKey(k.keyId);
      },
    }).then(after(`Key #${k.keyId} retired.`));

  const revoke = (k: KeyJson) =>
    void openDialog({
      title: k.status === 'REVOKED' ? `Move the compromise time of key #${k.keyId} earlier` : `Revoke key #${k.keyId}`,
      eyebrow: k.kid,
      danger: true,
      body: h(
        'p',
        { class: 'dialog__text' },
        'Codes recorded before the compromise time (or before now, when none is given) stay trusted; every later code signed by this key verifies as INVALID SIGNATURE. A compromise time can only be moved earlier.',
      ),
      fields: [
        { name: 'reason', label: 'Reason', kind: 'textarea', required: true, maxlength: 500 },
        { name: 'compromisedAt', label: 'Compromised at (UTC, optional)', kind: 'datetime', hint: 'Leave empty if the key was not compromised.', required: k.status === 'REVOKED' },
      ],
      validate: (v) => {
        const t = compromiseTime(v.compromisedAt, ctx.now());
        return t.ok ? null : t.error;
      },
      phrase: confirmationPhrase('revoke-key', k.keyId),
      confirmLabel: 'Revoke key',
      submit: async (v) => {
        const t = compromiseTime(v.compromisedAt, ctx.now());
        await ctx.api.revokeKey(k.keyId, v.reason.trim(), t.ok && t.iso ? t.iso : undefined);
      },
    }).then(after(`Key #${k.keyId} revoked.`));

  return h(
    'div',
    { class: 'view view--keys' },
    pageHeader({
      eyebrow: 'Security',
      title: 'Signing keys',
      lead: 'Ed25519 keys held by the key provider. Each code names its key id; historical codes always verify against the key that signed them.',
      actions: manage ? [button('Rotate key', { kind: 'primary', onClick: rotate, testId: 'key-rotate' })] : [],
    }),
    table(
      [
        { label: 'Key', cell: (k) => mono(`#${k.keyId}`), kind: ['nowrap'] },
        { label: 'Status', cell: (k) => statusMark(humanize(k.status), toneOf('key', k.status)), kind: ['nowrap'] },
        { label: 'Kid', cell: (k) => mono(k.kid), kind: ['nowrap'] },
        {
          label: 'Public key (base64url)',
          cell: (k) => h('span', { class: 'keycell' }, mono(k.publicKey, shortHash(k.publicKey, 14, 6)), copyButton(k.publicKey, 'Copy')),
          kind: ['wide', 'nowrap'],
        },
        { label: 'Provider', cell: (k) => humanize(k.provider), kind: ['nowrap'] },
        {
          label: 'Lifetime',
          cell: (k) =>
            h(
              'span',
              { attrs: { title: k.revocationReason ?? '' } },
              `From ${formatDateTime(k.activatedAt)}`,
              k.revokedAt
                ? h('span', { class: 'cell-sub' }, `Revoked ${formatDateTime(k.revokedAt)}${k.compromisedAt ? ` · compromised ${formatDateTime(k.compromisedAt)}` : ''}`)
                : k.retiredAt
                  ? h('span', { class: 'cell-sub' }, `Retired ${formatDateTime(k.retiredAt)} · verify only`)
                  : h('span', { class: 'cell-sub' }, 'Signing'),
            ),
          kind: ['nowrap'],
        },
        ...(manage
          ? [
              {
                label: '',
                kind: ['actions' as const],
                cell: (k: KeyJson) => {
                  const a = keyActions(k);
                  return h(
                    'span',
                    { class: 'row-actions' },
                    a.canRetire ? button('Retire', { kind: 'ghost', onClick: () => retire(k), testId: `key-retire-${k.keyId}` }) : null,
                    button(k.status === 'REVOKED' ? 'Amend' : 'Revoke', { kind: 'ghost', onClick: () => revoke(k), testId: `key-revoke-${k.keyId}` }),
                  );
                },
              },
            ]
          : []),
      ],
      keys,
      { empty: 'No key. Rotate to create the first signing key.', caption: 'Signing keys' },
    ),
    h('p', { class: 'footnote' }, 'Public keys are also published at /.well-known/orbes-keys.json for independent verification.'),
  );
}
