/**
 * ORBES counterfeit simulation (master spec §27).
 *
 *   npx tsx scripts/counterfeit-simulation.ts [--only 2,8] [--no-write] [--out <file>]
 *
 * Runs the scenarios of test/simulation/scenarios.ts — the same code the
 * vitest suite (test/simulation/*.test.ts) runs — each in its own world
 * (in-memory PGlite, memory keys, the real services and HTTP app), and writes
 * docs/reports/counterfeit-simulation.md: per scenario a table
 * check → expected → observed → result, the anomaly records the run created,
 * the key numbers, the documented gaps and what the system can and cannot
 * detect.
 *
 * Outcomes are deterministic (seeded cameras, fixed clock, fixed scenario
 * order). Signing keys and nonces are random per run, so the printed bytes
 * and the timings differ from run to run; the states do not.
 * Exit code 0 iff no check FAILs and the gaps / limits are the documented ones.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { DEFAULT_ANOMALY_CONFIG } from '../src/server/config.js';
import { ANOMALY_WEIGHTS } from '../src/server/services/anomaly-rules.js';
import { ARTIFACT_DPI, ARTIFACT_WIDTH_MM, BURST_FRAMES, DEVICE_PRESETS, median, type Check } from '../test/simulation/lab.js';
import { runScenario, SCENARIOS, unexpected, type Scenario, type ScenarioResult } from '../test/simulation/scenarios.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_OUT = resolve(HERE, '..', '..', 'docs', 'reports', 'counterfeit-simulation.md');

// ── Formatting ─────────────────────────────────────────────────────────────

const cell = (s: unknown): string => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const pct = (n: number, d: number): string => (d === 0 ? '—' : `${((100 * n) / d).toFixed(n === d ? 0 : 1)} %`);
const count = (rs: readonly ScenarioResult[], status: Check['status']): number => rs.reduce((n, r) => n + r.checks.filter((c) => c.status === status).length, 0);

function p95(xs: readonly number[]): number {
  if (xs.length === 0) return 0;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.ceil(0.95 * s.length) - 1)];
}

function result(c: Check): string {
  return c.status === 'PASS' ? 'PASS' : `**${c.status}**`;
}

function anomalyDetails(d: Record<string, unknown>): string {
  const skip = new Set(['scanEventId', 'weight', 'decay']);
  return Object.entries(d)
    .filter(([k]) => !skip.has(k))
    .map(([k, v]) => `${k} ${Array.isArray(v) ? v.join('·') : String(v)}`)
    .join(', ');
}

// ── Report ─────────────────────────────────────────────────────────────────

function report(results: readonly ScenarioResult[], scenarios: readonly Scenario[], meta: { startedAt: Date; durationMs: number; partial: boolean }): string {
  const L: string[] = [];
  const all = results.flatMap((r) => r.checks);
  const photos = results.reduce((n, r) => n + r.captures.photos, 0);
  const decoded = results.reduce((n, r) => n + r.captures.decoded, 0);
  const frames = results.reduce((n, r) => n + r.captures.frames, 0);
  const decodeMs = results.flatMap((r) => r.captures.decodeMs);
  const responses = results.reduce((n, r) => n + r.responses, 0);
  const forged = results.reduce((n, r) => n + r.forged.submissions, 0);
  const forgedAuthentic = results.reduce((n, r) => n + r.forged.authentic, 0);
  const genome: Record<string, number> = {};
  for (const r of results) for (const [k, v] of Object.entries(r.genomeChecks)) genome[k] = (genome[k] ?? 0) + v;
  const genuineScans = Object.values(genome).reduce((a, b) => a + b, 0);
  const states = [...new Set(results.flatMap((r) => r.states))].sort();
  const redaction = all.filter((c) => /z$/.test(c.id));
  const anomalies = results.flatMap((r) => r.anomalies.map((a) => ({ ...a, scenario: r.id })));
  const fails = count(results, 'FAIL');
  const surprises = results.flatMap((r) => unexpected(scenarios.find((s) => s.id === r.id)!, r));

  L.push('# ORBES — counterfeit simulation (master spec §27)', '');
  L.push(
    `Generated by \`npx tsx scripts/counterfeit-simulation.ts\` on ${meta.startedAt.toISOString().slice(0, 10)} in ${(meta.durationMs / 1000).toFixed(0)} s${meta.partial ? ' (**partial run**: `--only`)' : ''}. ` +
      'The same scenarios run in CI as `npx vitest run test/simulation` (files `test/simulation/*.test.ts`, scenario code in `test/simulation/scenarios.ts`, harness in `test/simulation/lab.ts`).',
    '',
  );
  L.push(
    `**Result:** ${all.length} checks in ${results.length} scenarios — ${count(results, 'PASS')} PASS, ${count(results, 'GAP')} GAP, ${count(results, 'LIMIT')} LIMIT, ${fails} FAIL. ` +
      (surprises.length === 0 ? 'Every GAP and LIMIT is a documented one (below).' : `**${surprises.length} unexpected outcome(s)** — see the tables.`),
    '',
  );
  if (surprises.length > 0) {
    L.push(`> **Warning:** ${surprises.length} check(s) did not come out as documented (${surprises.map((c) => c.id).join(', ')}). The narrative sections below describe the documented behaviour and may not match this run.`, '');
  }
  L.push('- **PASS** — the expectation of §27 holds.');
  L.push('- **GAP** — §27 expected a different public state; the observed one is what the normative platform contract (`genome/PLATFORM-CONTRACTS.md` §2.4/§2.5) prescribes. Never an AUTHENTIC* answer to a forgery; listed under *Gaps*.');
  L.push('- **LIMIT** — the system behaves as designed but does not catch this counterfeit (a detection limit, e.g. one quiet copy).');
  L.push('- **FAIL** — anything else.', '');

  L.push('## Summary', '');
  L.push('| # | Scenario | Checks | PASS | GAP | LIMIT | FAIL | Photos (decoded) | Verify responses | Time |');
  L.push('|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|');
  for (const r of results) {
    const n = (s: Check['status']) => r.checks.filter((c) => c.status === s).length;
    L.push(
      `| ${r.id} | ${cell(r.title)} | ${r.checks.length} | ${n('PASS')} | ${n('GAP')} | ${n('LIMIT')} | ${n('FAIL')} | ${r.captures.photos} (${r.captures.decoded}) | ${r.responses} | ${(r.durationMs / 1000).toFixed(1)} s |`,
    );
  }
  L.push(`| | **Total** | **${all.length}** | **${count(results, 'PASS')}** | **${count(results, 'GAP')}** | **${count(results, 'LIMIT')}** | **${fails}** | **${photos} (${decoded})** | **${responses}** | |`, '');

  L.push('## Key numbers', '');
  const forgedStates = mergeTallies(results.map((r) => r.forged.states)) || '—';
  L.push(
    `- **Forgeries accepted: ${forgedAuthentic} of ${forged}.** ${forged} verification responses were for byte strings that are not an issued code (edited identity, genome version or signature; codes signed by a foreign, stolen or revoked key; corrupted frames; seeded random codes)${forgedAuthentic === 0 ? ', and none was answered AUTHENTIC*' : ''}. Their states: ${forgedStates}.`,
  );
  const missed = results.filter((r) => r.captures.photos > r.captures.decoded).map((r) => `scenario ${r.id}: ${r.captures.photos - r.captures.decoded}`);
  const onlyDamage = missed.length === 1 && results.find((r) => r.id === 6)?.checks.find((c) => c.id === '6a')?.status === 'PASS' && photos - decoded === 1;
  L.push(
    `- **Phone captures:** ${photos} simulated photographs (${frames} frames, bursts of up to ${BURST_FRAMES}) of genuine, copied, forged and damaged ${ARTIFACT_WIDTH_MM} mm / ${ARTIFACT_DPI} dpi PNG artifacts; ${decoded} decoded (${pct(decoded, photos)}). ` +
      (onlyDamage ? 'The only photo not decoded is the label deliberately damaged beyond Reed-Solomon capacity (6a). ' : missed.length ? `Not decoded: ${missed.join(', ')}. ` : '') +
      `Decoder time per frame: median ${median(decodeMs).toFixed(0)} ms, p95 ${p95(decodeMs).toFixed(0)} ms (this machine, single thread).`,
  );
  L.push(`- **Genome cross-check on genuine prints:** ${genuineScans} camera scans of unaltered genuine artifacts → ${Object.entries(genome).sort().map(([k, v]) => `${k} ${v}`).join(', ')}. **${genome.MISMATCH ?? 0} false GENOME_MISMATCH.** (INCONCLUSIVE = fewer than 6 glyphs read with confidence ≥ 0.5, never flags; NOT_PROVIDED = the decision ended before the cross-check, e.g. a revoked key.)`);
  L.push(`- **Redaction:** ${responses} public responses checked field by field against the contract's allow-list for their state, for internal vocabulary (risk, score, threshold, reasons, anomaly types), raw product/code statuses and the world's secrets (row ids, payload hashes, claim codes, account ids): ${redaction.every((c) => c.status === 'PASS') ? '**0 leaks**' : '**LEAKS FOUND**'}. States covered: ${states.join(', ')} (${states.length} of 9).`);
  const byType = new Map<string, number>();
  for (const a of anomalies) byType.set(`${a.type} (${a.severity})`, (byType.get(`${a.type} (${a.severity})`) ?? 0) + 1);
  L.push(`- **Anomaly records created:** ${anomalies.length} — ${[...byType].map(([k, v]) => `${k} ×${v}`).join(', ')}.`, '');

  L.push('## Results per scenario', '');
  for (const r of results) {
    L.push(`### ${r.id}. ${r.title}`, '', r.setup, '');
    L.push('| # | Check | Expected | Observed | Result |', '|---|---|---|---|---|');
    for (const c of r.checks) L.push(`| ${c.id} | ${cell(c.title)} | ${cell(c.expected)} | ${cell(c.observed)} | ${result(c)} |`);
    const notes = r.checks.filter((c) => c.note);
    if (notes.length) {
      L.push('');
      for (const c of notes) L.push(`- *${c.id}:* ${c.note}`);
    }
    L.push('');
    L.push(`Anomaly records: ${r.anomalies.length === 0 ? 'none.' : r.anomalies.map((a) => `${a.type} ${a.severity} ×${a.occurrences}`).join(' · ')}`, '');
  }

  L.push('## Anomaly records created', '');
  L.push(
    'As listed by `GET /api/admin/anomalies` at the end of each scenario (internal, admin-only data: the risk score and details never reach a public response). `Occurrences` counts the scans that re-triggered the same open finding; `Risk` is the stored (maximum, decayed) contribution of the finding.',
    '',
  );
  if (anomalies.length === 0) L.push('None.', '');
  else {
    L.push('| Scenario | World | Product | Type | Severity | Occurrences | Risk | Status | Details (last occurrence) |', '|---:|---|---|---|---|---:|---:|---|---|');
    for (const a of anomalies) {
      L.push(`| ${a.scenario} | ${cell(a.world)} | ${cell(a.productId ?? '— (unregistered)')} | ${a.type} | ${a.severity} | ${a.occurrences} | ${a.riskScore} | ${a.status} | ${cell(anomalyDetails(a.details))} |`);
    }
    L.push('');
  }

  const W = ANOMALY_WEIGHTS;
  const D = DEFAULT_ANOMALY_CONFIG;
  const combined = Math.round(100 * (1 - (1 - W.SCAN_VELOCITY.weight / 100) * (1 - W.DEVICE_DIVERSITY.weight / 100)));
  L.push('## Gaps against §27', '');
  L.push('Each gap is a place where the §27 scenario list expects a different public state than the one the normative platform contract prescribes and the implementation returns. None makes a forgery look authentic. They are reported, not fixed: the behaviour is specified in `PLATFORM-CONTRACTS.md` and owned outside this suite.', '');
  L.push(
    `1. **4a — altered genome version answers MALFORMED_CODE, not INVALID_SIGNATURE.** \`src/server/services/verification.ts:361-363\` (contract §2.4 step 2) rejects an unsupported genome version before the key lookup and the signature check (steps 3–4); version 0 is already rejected by strict payload parsing. The forged code is refused, but the public copy is “UNREADABLE CODE — please scan it again”, which invites the user to rescan a code that was read perfectly. The POC (\`scripts/poc.ts\` \`decideVerification\`) checks the signature first and reports INVALID_SIGNATURE. Suggested fix (contract owner): verify the signature before the version check, or answer INVALID_SIGNATURE for unsupported versions.`,
  );
  L.push(
    `2. **9b — a velocity burst confined to one place is never shown as SUSPICIOUS with the default thresholds.** SCAN_VELOCITY (${W.SCAN_VELOCITY.weight}) and DEVICE_DIVERSITY (${W.DEVICE_DIVERSITY.weight}) (\`src/server/services/anomaly-rules.ts:40-41\`) combine to 100·(1 − 0.65·0.70) = ${combined}, below \`suspiciousThreshold\` ${D.suspiciousThreshold} (\`src/server/config.ts:63\`). 30 scans by 15 phones in 15 minutes in Paris are recorded as two MEDIUM anomalies for review, while every scanner keeps seeing AUTHENTIC — FIRST REGISTRATION (and a registration token). A burst needs a geographic signal (scenario 2) or an operator threshold ≤ ${combined} (9e shows threshold 50 flags it). Suggested: raise one of the two weights or lower the default threshold, after checking the false-positive cost on real traffic.`,
  );
  L.push(
    '3. **10l — a new forgery signed by a revoked key for an unregistered identity answers UNKNOWN, not INVALID_SIGNATURE.** `verification.ts:376-399` runs the registry lookup (step 5: UNKNOWN + CRITICAL `VALID_SIGNATURE_UNREGISTERED`) before the revoked-key rule (step 6), exactly as contract §2.4 orders them (and as `test/verification/verification.test.ts` asserts). `docs/CRYPTOGRAPHY.md:136`, `docs/THREAT-MODEL.md:108` and `docs/SECURITY-MODEL.md:34` however state that anything else signed by a revoked key is INVALID SIGNATURE / fails. Likewise 10m (existing identity) answers SUSPICIOUS_ACTIVITY (CODE_MISMATCH). Not authentic either way; the documents and the contract should be reconciled.',
    '',
  );
  L.push('Minor observation (no gap): `verifyInputSchema` in `src/server/services/verification.ts:150-173` says undecodable codes “must reach the service” (any string ≤ 1 KiB), but the route validates with the stricter `verifyBody` (`src/server/http/schemas.ts:116`): empty, > 200 characters or non-base64url codes get `400 VALIDATION_FAILED` and are not recorded (6j). That matches `docs/API.md` (verify request rules), so only the service-level comment / unused schema is stale.', '');

  L.push('## What the system can and cannot detect', '');
  L.push('**Detected (forgeries are never AUTHENTIC*):**', '');
  L.push('- Any edit of the signed bytes — product identity (every single-bit flip), genome version, issue, nonce, signature (every one of the 512 bits), signature transplanted from another genuine code — whether submitted directly or printed as a new, perfectly decodable artifact (3, 4a, 5).');
  L.push('- Codes signed by any key ORBES does not hold: an unknown key id, the forger’s own key, 203 seeded random codes (100 raw, 100 with a well-formed payload, 3 more printed and photographed; 10a, 10b, 10g–10i).');
  L.push('- Codes signed with a **stolen** real key: UNKNOWN + CRITICAL `VALID_SIGNATURE_UNREGISTERED` for a new identity, SUSPICIOUS + CRITICAL `CODE_MISMATCH` for an existing product (registry nonce / payload-hash match). After revocation with a compromise time, codes recorded before it keep verifying and later ones answer INVALID_SIGNATURE; re-issue under the new key restores the product (10c–10p).');
  L.push('- Printed genome glyphs that disagree with the signed identity in ≥ 2 of ≥ 6 confidently read positions: SUSPICIOUS + `GENOME_MISMATCH` (4c).');
  L.push('- Revoked products, revoked and superseded codes (REVOKED + `POST_REVOCATION_SCAN`), with re-issue producing a new authentic artifact (7).');
  L.push(`- A copied code once it is scanned in ways one object cannot be: two places farther than ${D.minTravelKm} km apart faster than ${D.impossibleTravelKmh} km/h (IMPOSSIBLE_TRAVEL, from city coordinates or, conservatively, country centroids minus country radii), more than ${D.geoMaxCountries} countries in ${D.geoWindowDays} days (GEO_DISPERSION). The logged-in owner keeps OWNERSHIP VERIFIED with an unusual-activity notice (2, 8, 9f–9h).`);
  L.push('- Unreadable or malformed codes: no request at all when Reed-Solomon fails; MALFORMED_CODE for bad CRC, length or payload fields; 400 for requests outside the schema (6).', '');
  const memoryH = Math.max(0, (1 - (D.suspiciousThreshold - 0.5) / W.IMPOSSIBLE_TRAVEL.weight) * D.decayDays * 24);
  const parisTokyoH = 9705 / D.impossibleTravelKmh;
  L.push('**Not detected (by design or by limit):**', '');
  L.push(
    `- **A single quiet copy.** A perfect copy of a genuine code (the bytes and the genome are public once photographed) verifies exactly like the original as long as its scans are plausible for one object: the first scan anywhere (2b, 8a), or two copies scanned in alternation more than ${parisTokyoH.toFixed(1)} h apart between Paris and Tokyo (9 705 km at ${D.impossibleTravelKmh} km/h; 8g, 8h). A printed code proves that ORBES issued the identity, never that the object in hand is the original.`,
  );
  L.push(`- **Short memory of one finding.** One IMPOSSIBLE_TRAVEL finding (weight ${W.IMPOSSIBLE_TRAVEL.weight}) flags scans only while its linearly decayed weight still rounds to ≥ ${D.suspiciousThreshold}: with ${D.decayDays}-day decay that is the next ≈ ${memoryH.toFixed(0)} hours (8g). The anomaly record stays OPEN for review.`);
  L.push(`- **Volume without geography** (9b, gap 2 above): bursts in one city are recorded, not shown.`);
  L.push('- **Partial genome forgery.** One replaced glyph is tolerated as a misread (4d); a genome ring made illegible (sanded, smudged, fewer than 6 confident glyphs) is INCONCLUSIVE and never flags (4e). The genome check also depends on the client: a request without a genome reading is NOT_PROVIDED.');
  L.push('- **Who scans first.** While a product is unregistered, whoever scans any copy first is offered a registration token. The claim code shipped with the genuine piece is what stops the copy’s holder from registering (8f); products issued without a claim code have no such protection. Once the genuine buyer registers, every copy shows AUTHENTIC — REGISTERED (not to its holder) — the registration conflict is the visible signal (8j).');
  L.push('- **Rejected forgeries are not anomalies.** INVALID_SIGNATURE and MALFORMED_CODE scans are stored as scan / authentication events (visible under VERIFICATION EVENTS) but create no anomaly record, so a flood of invalid forgeries does not raise an alert by itself (3g).');
  L.push('- **Geo depends on the edge.** Location comes from proxy headers (GEO_MODE=headers here); without them (GEO_MODE=none) none of the travel or dispersion rules can fire.', '');

  L.push('## Method', '');
  L.push(
    `- **Real stack.** Every scenario opens a fresh world: \`createContext\` (in-memory PGlite with all migrations, \`MemoryKeyProvider\`, every service) + \`buildApp\`, driven with \`app.inject\`. Products are issued, activated, revoked and re-issued, keys rotated and revoked through the **admin API** (an ADMIN session). Genuine artifacts are downloaded from \`GET /api/admin/codes/:codeId/artifact.png\` (${ARTIFACT_WIDTH_MM} mm, ${ARTIFACT_DPI} dpi, ≈ 14 px per code unit). Forged artifacts are produced by the server's own render module (\`renderArtifact\`) from the forger's bytes and glyphs.`,
  );
  L.push(
    `- **Phones.** Each device has its own cookie jar (\`orbes_device\` → device pseudonym), IP and location; the edge geo headers (GEO_MODE=headers, trusted proxy) carry city coordinates and the country, or the country only (9f–9h). Captures use the deterministic camera simulator (\`test/support/camera-sim.ts\`) with a preset per device cycling through ${DEVICE_PRESETS.join(', ')} (the \`metal\` preset is left out: 55 % in the scan matrix), a seeded random rotation, ±4° extra tilt and offset; a scan is a burst of up to ${BURST_FRAMES} frames drifting 1.5°. Each frame goes through the scanner worker's decode step (\`src/web/verify/frame-decoder.ts\` → core decoder, genome reading on), and the request body is built by the scanner's own \`buildVerifyInput\` (\`src/web/verify/capture.ts\`).`,
  );
  L.push('- **Forger.** Byte-level attacks start from what a real scan of the genuine label read, edit it, and recompute the CRC-16 (it is public). Theft of the signing key is simulated by signing with the world\'s real private key outside issuance (`MemoryKeyProvider.sign`). Random codes come from a seeded PRNG (raw 79-byte strings; and frames whose payload parses as CODE-01/GENOME-01 naming the live key, by rejection sampling).');
  L.push('- **Time.** One manual clock per world, starting 2026-06-01 08:00 UTC and only moving forward; travel and decay scenarios set it explicitly (times in the tables are UTC). Anomaly thresholds are the production defaults (`DEFAULT_ANOMALY_CONFIG`) except in the second world of 9e.');
  L.push('- **Evidence.** Public state and body from the HTTP response; the internal reason list and genome check from `authentication_events` (to prove a state was reached for the claimed reason); anomalies from the admin API.', '');

  L.push('## Limitations', '');
  L.push('- The camera is simulated (perspective, lens, blur, noise, glare, occlusion, texture, JPEG) — no real phone, printer, ink spread or substrate. Decode robustness is measured separately in `docs/reports/scan-matrix.md`; here it only has to be good enough to carry the attacks.');
  L.push('- Frames are decoded whole (the upload path); the live scanner\'s canvas crop/scale step is browser-only and not exercised. The browser itself is covered by the Playwright E2E tests, not here.');
  L.push('- Scale is small: tens of devices per scenario, one product per attack. Rate limits are the test configuration (10 000/min); production limits (60 verify/min per IP) would throttle the bursts of 3, 5 and 10 from a single forger device.');
  L.push('- Geolocation is taken at face value from the trusted-proxy headers; spoofed or VPN locations, and the IP-to-location accuracy of a real edge, are out of scope.');
  L.push('- PGlite runs one connection, so scans are serialised. `test/simulation/postgres.test.ts` runs scenarios 2, 8 and 10 on real PostgreSQL when `ORBES_TEST_POSTGRES_URL` is set (role with CREATEDB); this report was generated on PGlite.');
  L.push('- Key material and nonces are random per run, so artifacts differ between runs; states, anomaly types and counts are stable. Timings are wall-clock on the generating machine.');
  L.push('- Expectations are those of the §27 scenario list as briefed for this suite; where the platform contract says otherwise the check is a GAP, not silently re-aligned.', '');

  L.push('## Reproduce', '', '```sh', 'cd genome', 'npx tsx scripts/counterfeit-simulation.ts          # all scenarios, writes this report', 'npx tsx scripts/counterfeit-simulation.ts --only 8 --no-write', 'npx vitest run test/simulation                     # the same scenarios as tests', '```', '');
  return L.join('\n');
}

/** Merge "A ×2, B ×1" strings. */
function mergeTallies(parts: readonly string[]): string {
  const m = new Map<string, number>();
  for (const p of parts) {
    for (const item of p.split(', ')) {
      const match = /^(.*) ×(\d+)$/.exec(item.trim());
      if (match) m.set(match[1], (m.get(match[1]) ?? 0) + Number(match[2]));
    }
  }
  return [...m].sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ×${v}`).join(', ');
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main(): Promise<number> {
  const { values } = parseArgs({
    options: { only: { type: 'string' }, 'no-write': { type: 'boolean', default: false }, out: { type: 'string' } },
  });
  const only = values.only ? values.only.split(',').map((s) => Number(s.trim())) : undefined;
  const selected = only ? SCENARIOS.filter((s) => only.includes(s.id)) : [...SCENARIOS];
  if (selected.length === 0) throw new Error(`no scenario matches --only ${values.only}`);
  const startedAt = new Date();
  const t0 = performance.now();
  const results: ScenarioResult[] = [];
  for (const s of selected) {
    process.stdout.write(`scenario ${String(s.id).padStart(2)} ${s.title} … `);
    const r = await runScenario(s);
    results.push(r);
    const n = (st: Check['status']) => r.checks.filter((c) => c.status === st).length;
    const bad = unexpected(s, r);
    console.log(`${(r.durationMs / 1000).toFixed(1)} s · ${n('PASS')} pass, ${n('GAP')} gap, ${n('LIMIT')} limit, ${n('FAIL')} fail${bad.length ? ' · UNEXPECTED' : ''}`);
    for (const c of bad) console.log(`    ${c.status} ${c.id} ${c.title}: expected ${c.expected}, observed ${c.observed}`);
  }
  const md = report(results, selected, { startedAt, durationMs: performance.now() - t0, partial: !!only });
  const out = values.out ? resolve(values.out) : DEFAULT_OUT;
  if (!values['no-write']) {
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, md);
    console.log(`report: ${relative(process.cwd(), out) || out}`);
  }
  const surprises = results.flatMap((r) => unexpected(selected.find((s) => s.id === r.id)!, r));
  console.log(surprises.length === 0 ? 'all checks as expected' : `${surprises.length} unexpected check(s)`);
  return surprises.length === 0 ? 0 : 1;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().then(
    (code) => process.exit(code),
    (e) => {
      console.error(e);
      process.exit(2);
    },
  );
}

export { report };
